export interface Producto {
    id?:string;
    id_foraneo?:string;
    cod_barra?:string;
    cod_barra_alterno?:string;
    codigo_alterno_1?:string;
    codigo_alterno_2?:string;
    descripcion?:string;
    descripcion_larga?:string;
    precio?:string;
    observacion?:string;
    marca?:string;
    presentacion?:string;
    medida?:string;
    concentracion?:string;
    estado_item_bodega?:string;
    estado_del?:string;
    cantidad?:string;
    nome_token?:string;
    created_at?:string;
    updated_at?:string;
}
